---
title: TAMIMI's BLOG
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: A blog to share what I know.
disqus_shortname: disqus_lxON8o0NMV
reading_time: true
words_per_minute: 200
url: http://tamim.io
owner:
  name: Ahmad Tamimi
  avatar: avatar.jpg
  bio: I'm engineer, entrepreneur, like to try new things, so expect a smoothie mix
    blog.
  email: eng.ahmad@tamim.io
  twitter: https://twitter.com/engr_tamimi
  facebook: 
  github: 
  stackexchange: 
  linkedin: 
  instagram: 
  flickr: 
  tumblr: 
  google_plus: 
background: 
google_analytics: UA-60390950-1
google_verify: 
bing_verify: 
future: true
highlighter: pygments
markdown: kramdown
gems:
- jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed
permalink: "/:categories/:title/"
paginate: 5
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true
  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class
include:
- ".htaccess"
exclude:
- lib
- config.rb
- Capfile
- config
- Gemfile
- Gemfile.lock
- README.md
- LICENSE
- log
- Rakefile
- Rakefile.rb
- tmp
- less
- "*.sublime-project"
- "*.sublime-workspace"
- test
- spec
- Gruntfile.js
- package.json
- node_modules
